# -*- coding: utf-8 -*-
"""nlp_with_nltk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fjjcMcwZrRA7vJEB8-zwLAPlG6JpKcC
"""

!pip install nltk
# import nltk
# nltk.download('punkt')

corpus="""Hello Welcome, to technical world.
Please be humble for everyone! to gain the respect from others."""

print(corpus)

"""# Tokenization

Sentence --> Paragraph
"""

from nltk.tokenize import sent_tokenize
documents = sent_tokenize(corpus)
print(documents)

for sentence in documents:
    print(sentence)

"""paragraph --> words"""

from nltk.tokenize import word_tokenize
word_tokenize(corpus)

from nltk.tokenize import wordpunct_tokenize
word_tokenize(corpus)

from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
tokenizer.tokenize(corpus)

"""# Stemming

it is the process of reducing inflected form of a word to one so-called “stem,” or root form, also known as a “lemma” in linguistics.1 It is one of two primary methods—the other being lemmatization—that reduces inflectional variants within a text dataset to one morphological lexeme. In doing so, stemming aims to improve text processing in machine learning and information retrieval systems.
"""

## Classification Problem
## Comments of products is a positive review or negative review
## Reviews --> [eating, eat, eaten] => eat

words=["eating","eats","eaten","writing","writes","programming","programs","history","finally","finalized"]

"""####PorterStemmer"""

from nltk.stem import PorterStemmer
stemming = PorterStemmer()

for word in words:
  print(word + "-->"+stemming.stem(word))

"""####RegexpStemmer class

NLTK has RegexpStemmer class with the help of which we can easily implement Regular Expression Stemmer algorithms. It basically takes a single regular expression and removes any prefix or suffix that matches the expression. Let us see an example
"""

from nltk.stem import RegexpStemmer
reg_stemmer = RegexpStemmer('ing$|s$|e$|able$', min=4)

reg_stemmer.stem('eating')

"""####Snowball Stemmer

It is a stemming algorithm which is also known as the Porter2 stemming algorithm as it is a better version of the Porter Stemmer since some issues of it were fixed in this stemmer.
"""

from nltk.stem import SnowballStemmer
snowballStemmer = SnowballStemmer('english')

for word in words:
  print(word + "-->"+ snowballStemmer.stem(word))

"""Stemmin is not good for the Chatbot. We use Lemmatization.

#Lemmatization

Lemmatization technique is like stemming. The output we will get after lemmatization is called ‘lemma’, which is a root word rather than root stem, the output of stemming. After lemmatization, we will be getting a valid word that means the same thing.

####Wordnet Lemmatizer

NLTK provides WordNetLemmatizer class which is a thin wrapper around the wordnet corpus. This class uses morphy() function to the WordNet CorpusReader class to find a lemma.
"""

## Examples:-  Q&A, Chatbots, Text summarization

from nltk.stem import WordNetLemmatizer
#nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

'''
POS-
      Noun - n
      Verb - v
      Adjective - a
      Adverb - r
'''

lemmatizer.lemmatize("going",pos='n')

lemmatizer.lemmatize("going",pos='v')

for word in words:
    print(word+"---->"+lemmatizer.lemmatize(word,pos='v'))

"""#Stop Words

Stop words are a set of commonly used words in any language. For example, in English, “the”, “is” and “and”, would easily qualify as stop words. In NLP and text mining applications, stop words are used to eliminate unimportant words, allowing applications to focus on the important words instead.

Data Cleaning process
"""

## Speech Of DR APJ Abdul Kalam
paragraph = """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

from nltk.stem import PorterStemmer

from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

stopwords.words('english')

from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

sentences = nltk.sent_tokenize(paragraph)
for sentence in sentences:
  print(sentence)

"""
#### Apply Stopwords And Filter And then Apply **Stemming**"""

for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words)  # converting all the list of words into sentences

sentences

"""#### Apply Stopwords And Filter And then Apply **Snowball Stemming**"""

from nltk.stem import SnowballStemmer
snowballstemmer=SnowballStemmer('english')

for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[snowballStemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words)  # converting all the list of words into sentences

sentences

from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[lemmatizer.lemmatize(word, pos='v') for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words)  # converting all the list of words into sentences

sentences

"""#Parts of Speech Tags"""

## Speech Of DR.APJ Abdul Kalam
paragraph = """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

import nltk
sentences=nltk.sent_tokenize(paragraph)

sentences

# nltk.download('averaged_perceptron_tagger')

## We will find the Pos Tag

for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[word for word in words if word not in set(stopwords.words('english'))]
    #sentences[i]=' '.join(words)# converting all the list of words into sentences
    pos_tag=nltk.pos_tag(words)
    print(pos_tag)

"Taj Mahal is a beautiful Monument".split()

print(nltk.pos_tag("Taj Mahal is a beautiful Monument".split()))

"""#Named Entity Recognition"""

sentence="The Eiffel Tower was built from 1887 to 1889 by Gustave Eiffel, whose company specialized in building metal frameworks and structures."

import nltk
words = nltk.word_tokenize(sentence)
words

tag_elements = nltk.pos_tag(words)
tag_elements

nltk.download('maxent_ne_chunker')
nltk.download('words')

"""#Different Types of Encoding

Text input --> Vectors

#### (1)One Hot Encoded
"""



